#!/bin/zsh

mkdir -p "$HOME/.config/nvim/lua/config"
mkdir -p "$HOME/.local/bin/scripts"
mkdir -p "$HOME/.vim/undodir"

# rc files
pushd rc_files
cur_dir=$(pwd)

for file in *; do
    if [[ -f $file ]] && [[ $file = *rc ]]; then
        ln -sf "$cur_dir/$file" "$HOME/.$file"
    fi
done

ln -sf "$cur_dir/tmux.conf" "$HOME/.tmux.conf"
ln -sf "$cur_dir/nvim_init.lua" "$HOME/.config/nvim/init.lua"
popd

# lua files
pushd lua/config
cur_dir=$(pwd)
for file in *; do
    if [[ -f $file ]] && [[ $file = *.lua ]]; then
        ln -sf "$cur_dir/$file" "$HOME/.config/nvim/lua/config/$file"
    fi
done
popd

ln -sf ./scripts/duck "$HOME/.local/bin/scripts/duck"

#### plugins check
nvim_dir="$HOME/.local/share/nvim/site/autoload"
mkdir -p "$nvim_dir"

if [ ! -f "$nvim_dir/plug.vim" ]; then
    read -r -p "Install vim-plug? [y/n] " response
    if [[ "$response" =~ ^([yY])$ ]]; then
        curl "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim" \
            -o "$nvim_dir/plug.vim"
        nvim -es -u init.vim -i NONE -c "PlugInstall" -c "qa"
    fi
fi

#bashmarks
cur_dir=$(pwd)
mkdir -p "$ZSH/custom/plugins/bashmarks"
ln -sf "$cur_dir/plugins/bashmarks.plugin.sh" \
    "$ZSH/custom/plugins/bashmarks/bashmarks.plugin.zsh"
