#!/bin/bash

cur_dir=$(pwd)

ln -sf "$cur_dir/rc_files/vimrc" "$HOME/.vimrc"
ln -sf "$cur_dir/rc_files/bashrc" "$HOME/.bashrc"
ln -sf "$cur_dir/rc_files/zshrc" "$HOME/.zshrc"
ln -sf "$cur_dir/rc_files/tmux.conf" "$HOME/.tmux.conf"

mkdir -p "$HOME/.config/nvim"
ln -sf "$cur_dir/rc_files/nvim_init.lua" "$HOME/.config/nvim/init.lua"

mkdir -p "$HOME/.config/nvim/lua"
ln -sf "$cur_dir/lua/nvim-lspconfig.lua" "$HOME/.config/nvim/lua/nvim-lspconfig.lua"
ln -sf "$cur_dir/lua/treesitter.lua" "$HOME/.config/nvim/lua/treesitter.lua"
ln -sf "$cur_dir/lua/nvim-cmp.lua" "$HOME/.config/nvim/lua/nvim-cmp.lua"

mkdir -p "$HOME/.local/bin"
mkdir -p "$HOME/.local/bin/scripts"
mkdir -p "$HOME/.vim/undodir"

ln -sf ./scripts/duck "$HOME/.local/bin/scripts/duck"

#### plugins check
nvim_dir="$HOME/.local/share/nvim/site/autoload"
mkdir -p "$nvim_dir"

if [ ! -f "$nvim_dir/plug.vim" ]; then
    read -r -p "Install vim-plug? [y/n] " response
    if [[ "$response" =~ ^([yY])$ ]]; then
        curl "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim" \
            -o "$nvim_dir/plug.vim"
        nvim -es -u init.vim -i NONE -c "PlugInstall" -c "qa"
    fi
fi

#bashmarks
mkdir -p "$ZSH/custom/plugins/bashmarks"
ln -sf "$cur_dir/plugins/bashmarks.plugin.sh" \
    "$ZSH/custom/plugins/bashmarks/bashmarks.plugin.zsh"
