export PATH=\
/usr/local/bin:\
/usr/bin:\
/bin:\
/usr/local/go/bin:\
$HOME/.local/bin/scripts:\
/usr/local/games:\
/usr/games
	
export OSH=$HOME/programs/bash/oh-my-bash

OSH_THEME="dulcie"

completions=(
  git
  composer
  ssh
)

aliases=(
  general
)

plugins=(
  git
  bashmarks
)

source $OSH/oh-my-bash.sh

alias '?'=duck

