export PATH=\
/usr/local/bin:\
/usr/bin:\
/bin:\
/usr/local/go/bin:\
$HOME/.local/bin/scripts:\
$HOME/.local/bin:\
$HOME/.cargo/bin:\
$HOME/.npm-global/bin:\
$HOME/programs/go/bin:\
$HOME/.dotnet
	
export OSH=$HOME/.oh-my-bash
export RUST_SRC_PATH="$(rustc --print sysroot)/lib/rustlib/src/rust/library"

OSH_THEME="garo"

completions=(
  git
  composer
  ssh
  dotnet
)

aliases=(
  general
)

plugins=(
  git
  bashmarks
)

source $OSH/oh-my-bash.sh

alias '?'=duck

source "$HOME/.cargo/env"

alias luamake=/home/yubs/programs/github_projects/sumneko/lua-language-server/3rd/luamake/luamake
. "$HOME/.cargo/env"
