export PATH=\
/usr/local/bin:\
/usr/bin:\
/bin:\
$GOPATH/bin:\
$HOME/.local/bin/scripts:

export ZSH=$HOME/programs/zsh/ohmyzsh
export GOPATH=$HOME/programs/go

ZSH_THEME="junkfood"

plugins=(git bashmarks)

source $ZSH/oh-my-zsh.sh

alias '?'=duck
alias luamake=/home/yubs/programs/github_projects/sumneko/lua-language-server/3rd/luamake/luamake
