export PATH=\
/usr/local/bin:\
/usr/bin:\
/bin:\
/Users/jason/go/bin:\
/usr/local/opt/python@3.7/bin

export ZSH=$HOME/.oh-my-zsh
export TERM=screen-256color

ZSH_THEME="zhann"

plugins=(git bashmarks)

source $ZSH/oh-my-zsh.sh

alias '?'=duck

